# Код, сгенерированный из ui файлов с помощью pyuic

from PyQt5 import QtCore, QtGui, QtWidgets


class EditorMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1950, 1090)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plain_text.setGeometry(QtCore.QRect(10, 10, 960, 1020))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        self.plain_text.setFont(font)
        self.plain_text.setStyleSheet("")
        self.plain_text.setObjectName("plain_text")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(980, 10, 960, 1020))
        self.image.setStyleSheet("")
        self.image.setText("")
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1950, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Latex editor"))


class SnippetsSettingsDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 780)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(750, 720, 239, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.grid_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout.setObjectName("grid_layout")
        self.delete_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_button.setObjectName("delete_button")
        self.grid_layout.addWidget(self.delete_button, 0, 3, 1, 1)
        self.ok_button = QtWidgets.QPushButton(self.layoutWidget)
        self.ok_button.setObjectName("ok_button")
        self.grid_layout.addWidget(self.ok_button, 0, 1, 1, 1)
        self.add_row_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_row_button.setObjectName("add_row_button")
        self.grid_layout.addWidget(self.add_row_button, 0, 2, 1, 1)
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setGeometry(QtCore.QRect(10, 10, 981, 701))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройка сниппетов"))
        self.delete_button.setText(_translate("Dialog", "Delete"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.add_row_button.setText(_translate("Dialog", "Add row"))


class SliderDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(180, 120)
        self.value_label = QtWidgets.QLabel(Dialog)
        self.value_label.setGeometry(QtCore.QRect(10, 40, 160, 20))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.value_label.setFont(font)
        self.value_label.setStyleSheet("")
        self.value_label.setText("")
        self.value_label.setObjectName("value_label")
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(90, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setGeometry(QtCore.QRect(10, 70, 75, 30))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.ok_button.setFont(font)
        self.ok_button.setObjectName("ok_button")
        self.slider = QtWidgets.QSlider(Dialog)
        self.slider.setGeometry(QtCore.QRect(10, 10, 160, 20))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Slider Window"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.ok_button.setText(_translate("Dialog", "OK"))


class AddThemeDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 339)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plain_text_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.plain_text_button.setFont(font)
        self.plain_text_button.setStyleSheet(
            "background: rgb(220, 220, 220); background: rgb(220, 220, 220); border-radius: 10px; height: 50px;\n"
            "border-width: 1px; border-style: solid; border-color: rgb(180, 180, 180);")
        self.plain_text_button.setObjectName("plain_text_button")
        self.gridLayout.addWidget(self.plain_text_button, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.text_color_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.text_color_button.setFont(font)
        self.text_color_button.setStyleSheet(
            "background: rgb(220, 220, 220); background: rgb(220, 220, 220); border-radius: 10px; height: 50px;\n"
            "border-width: 1px; border-style: solid; border-color: rgb(180, 180, 180);")
        self.text_color_button.setObjectName("text_color_button")
        self.gridLayout.addWidget(self.text_color_button, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.variables_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.variables_button.setFont(font)
        self.variables_button.setStyleSheet(
            "background: rgb(220, 220, 220); border-radius: 10px; height: 50px;\n"
            "border-width: 1px; border-style: solid; border-color: rgb(180, 180, 180);")
        self.variables_button.setObjectName("variables_button")
        self.gridLayout.addWidget(self.variables_button, 3, 1, 1, 1)
        self.background_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.background_button.setFont(font)
        self.background_button.setStyleSheet(
            "background: rgb(220, 220, 220); border-radius: 10px; height: 50px;\n"
            "border-width: 1px; border-style: solid; border-color: rgb(180, 180, 180);")
        self.background_button.setObjectName("background_button")
        self.gridLayout.addWidget(self.background_button, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(199, 280, 191, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ok_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ok_button.setObjectName("ok_button")
        self.gridLayout_2.addWidget(self.ok_button, 0, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_2.addWidget(self.cancel_button, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление темы"))
        self.plain_text_button.setText(_translate("Dialog", "Выбрать цвет"))
        self.label_2.setText(_translate("Dialog", "Цвет виджетов"))
        self.text_color_button.setText(_translate("Dialog", "Выбрать цвет"))
        self.label_4.setText(_translate("Dialog", "Задний фон"))
        self.label.setText(_translate("Dialog", "Подсветка"))
        self.label_3.setText(_translate("Dialog", "Цвет текста"))
        self.variables_button.setText(_translate("Dialog", "Выбрать цвет"))
        self.background_button.setText(_translate("Dialog", "Выбрать цвет"))
        self.ok_button.setText(_translate("Dialog", "OK"))
        self.cancel_button.setText(_translate("Dialog", " Cancel"))
